//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataExtractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscortTFSTicketTable_Prod
    {
        public string Escort_Name { get; set; }
        public string Escort_Requestor_Name { get; set; }
        public string ComponentImpacted { get; set; }
        public string Owner_Team { get; set; }
        public string Assigned_Team { get; set; }
        public Nullable<System.DateTime> Requested_Release_Date { get; set; }
        public string ClientLibVersion { get; set; }
        public string Component { get; set; }
        public string RCAStatus { get; set; }
        public string IncidentSeverity { get; set; }
        public string External_Milestone { get; set; }
        public string Team { get; set; }
        public Nullable<int> TSGID { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> ResolvedTime { get; set; }
        public Nullable<int> Effort { get; set; }
        public string KeywordSearch { get; set; }
        public string Closed_By { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string Resolved_Reason { get; set; }
        public string Resolved_By { get; set; }
        public Nullable<System.DateTime> Resolved_Date { get; set; }
        public string Activated_By { get; set; }
        public Nullable<System.DateTime> Activated_Date { get; set; }
        public Nullable<System.DateTime> State_Change_Date { get; set; }
        public string Board_Lane { get; set; }
        public string Board_Column_Done { get; set; }
        public string Board_Column { get; set; }
        public string Tags { get; set; }
        public Nullable<int> Related_Link_Count { get; set; }
        public string History { get; set; }
        public string Description { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Work_Item_Type { get; set; }
        public string Assigned_To { get; set; }
        public string Reason { get; set; }
        public string Changed_By { get; set; }
        public Nullable<int> Rev { get; set; }
        public Nullable<int> Watermark { get; set; }
        public Nullable<System.DateTime> Authorized_Date { get; set; }
        public string State { get; set; }
        public string Title { get; set; }
        public string Authorized_As { get; set; }
        public Nullable<int> Area_ID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> Changed_Date { get; set; }
        public Nullable<System.DateTime> Revised_Date { get; set; }
        public string Area_Path { get; set; }
        public string Node_Name { get; set; }
        public Nullable<int> Attached_File_Count { get; set; }
        public Nullable<int> Hyperlink_Count { get; set; }
        public string Team_Project { get; set; }
        public Nullable<int> External_Link_Count { get; set; }
        public Nullable<int> Iteration_ID { get; set; }
        public string Iteration_Path { get; set; }
        public string TFS_Migration_Id { get; set; }
        public Nullable<System.DateTime> Event_Time { get; set; }
        public string KPI_2_Description { get; set; }
        public string KPI_1_Description { get; set; }
        public string IcMID { get; set; }
        public Nullable<int> TFS_ID { get; set; }
        public string Purpose { get; set; }
        public string Cluster_Set { get; set; }
        public string Incident_Environment { get; set; }
    }
}
